### ISSUE TITLE
Project maintainership status.

### ISSUE THREAD

**Issue by vi** [cloudflare/boringtun#105]
Is it maintained? Is it recommended for real usage or only for testing?

> NOTE: This crate is still undergoing review for security concerns. Therefore, we recommend that you take caution before using it in a production application.

Is the review still going on, abandoned or complete? What is the result?

**Comment by vkrasnov** [comment]
The project is very much maintained, it is used exclusively by our deployment of the Warp app both server side, as well as on [Android](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US) and [iOS](https://apps.apple.com/us/app/1-1-1-1-faster-internet/id1423538627).

While we just launched, it is probably already the largest WireGuard deployment in the world. As we finish the post lunch polish, further improvements will be made, but it is 100% usable as is.

The internal review is complete, and all notable issues were fixed. Minor issues with no real security impact remain, the are tracked with the "security review" tag. In addition we plan to have an external audit of the project too.

**Comment by vi** [comment]
Then maybe it's time for BoringTun v1.0.0?

**Comment by vkrasnov** [comment]
Haha, that's a big commitment in the Rust world

**Comment by vi** [comment]
It's a commitment to bump version to 2.0.0 in case of incompatible changes.

**Comment by Ricordel** [comment]
So how should we take the warning note in the README?
> :warning: NOTE: This crate is still undergoing review for security concerns. Therefore, we recommend that you take caution before using it in a production application.

From previous comments, I understand we should have a look at issues tagged with `security-review` and decide for ourselves if we'll live with it, and otherwise we can consider it ready to use (knowing the other few bugs in the issues). Do you agree with that view?

**Comment by vkrasnov** [comment]
@Lekensteyn can you address this question?

**Comment by Lekensteyn** [comment]
Yes, I think that the note can be removed. The worst known issue at the moment is probably #53, but it does not cause security issues on itself.

**Comment by mpolden** [comment]
Any plans to release/tag a new version soon (not necessarily a 1.0.0), with the latest commits?
