### ISSUE TITLE
Wireguard connection stops working after adding 0.0.0.0/0 inside Docker container

### ISSUE THREAD

**Issue by Pyons** [cloudflare/boringtun#107]
I found this weird bug where when I add 0.0.0.0/0 to my allowedIPs on one of my peers the wireguard connection on the peer drops and is unrecoverable as far as I know. Bringing the wg interface down and up again does't work, I have to reboot the whole device.

My setup: 
I have borintun running inside a Docker container on a balena device and start it with:
`WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun WG_SUDO=1 wg-quick up wg0`

After trying for a while to see why this is happening I switched to:
`WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go  WG_SUDO=1 wg-quick up wg0`

and it is working just fine.

I still couldn't find out what exactly is causing this behaviour.

Please let me know how I can help to resolve this bug, because I would prefer using boringtun.

**Comment by nevelis** [comment]
I did this exact same thing today actually...  but it on a VM, using vanilla wireguard (ie: without boringtun).

So I think it's bad wireguard configuration, not a boringtun issue.
