### ISSUE TITLE
AtomicU64 for android

### ISSUE THREAD

**Issue by 3belut** [cloudflare/boringtun#114]
Hello,

When cross-compiling for arm-linux-androideabi with the Android NDK 21 i get te folowing error:

> error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
>  --> src\noise\rate_limiter.rs:9:25
>   |
> 9 | use std::sync::atomic::{AtomicU64, Ordering};
>   |                         ^^^^^^^^^
>   |                         |
>   |                         no `AtomicU64` in `sync::atomic`
>   |                         help: a similar name exists in the module: `AtomicU8`

According to the [Rust std documentation](https://doc.rust-lang.org/std/sync/atomic/#portability):

> The atomic types in this module may not be available on all platforms. The atomic types here are all widely available, however, and can generally be relied upon existing. Some notable exceptions are:
> 
> PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types.
> ARM platforms like armv5te that aren't for Linux do not have any atomics at all.
> ARM targets with thumbv6m do not have atomic operations at all.

I think AtomicU64 is not available on arm-linux-androideabi.

**Comment by vkrasnov** [comment]
@naga-cf do you know something about it?

**Comment by naga-cf** [comment]
Please use the target-triple `armv7a-linux-androideabi` for 32-bit and `aarch64-linux-android` for 64-bit since not all primitives are available on all instruction sets as you mentioned. 

https://developer.android.com/ndk/guides/other_build_systems#overview

**Comment by 3belut** [comment]
Thank you it worked, my mistake.
