### ISSUE TITLE
Official boringtun crate seems out-of-date

### ISSUE THREAD

**Issue by poupas** [cloudflare/boringtun#119]
Hi!

(First of all, thank you for creating this project.)

The boringtun crate has not been updated since March 22, 2019. In the meanwhile, many fixes and enhancements were pushed onto this repo. Is building from source the currently recommended way to use boringtun?

João

**Comment by kornelski** [comment]
pinging @ashleygwilliams who has publishing rights to that crate.

**Comment by vkrasnov** [comment]
Yes, the base code is stable for now, we should definitely make a release.

**Comment by vkrasnov** [comment]
Made a 0.3.0 release
