### ISSUE TITLE
using boringtun as windows WireGuard Client

### ISSUE THREAD

**Issue by flyfei-cmd** [cloudflare/boringtun#146]
hi, could I use boringtun as windows WireGuard Client?

**Comment by Noah-Kennedy** [comment]
We do not currently support windows, but may do so in the future

**Comment by fawazahmed0** [comment]
You can consider using this:
https://www.wiresock.net/

**Comment by Noah-Kennedy** [comment]
We may support windows via wintun at some point.

**Comment by tubzby** [comment]
Is there any progress or timeline for this feature?

**Comment by Noah-Kennedy** [comment]
No unfortunately. Because of the way windows works, this is actually a ton of work to do sadly.

**Comment by 3aaber** [comment]
Hi, if there is no available version of boringtun for windows, how cloudflare WARP is working on windows? does it use another library?
