### ISSUE TITLE
Boringtun fails to start on Apple Silicon

### ISSUE THREAD

**Issue by richiksc** [cloudflare/boringtun#161]
`boringtun` compiles succesfully with `cargo install --locked --path .` on `master` with Rust v1.49 on Apple Silicon.

However, when running with `boringtun utun`, I get the following message:

```
Boringtun failed to start.
```

---

Related: Homebrew/homebrew-core#68301

**Comment by vkrasnov** [comment]
Did you run with `sudo`?

**Comment by vkrasnov** [comment]
If so, can you try `sudo boringtun -f utun` and tell me if it prints something?

**Comment by richiksc** [comment]
No, I did not run with `sudo`. Running `sudo boringtun utun` works perfectly.

**Comment by vkrasnov** [comment]
It would print if there were errors :)

**Comment by chenrui333** [comment]
@vkrasnov is `sudo` behavior change documented anywhere?

**Comment by Noah-Kennedy** [comment]
@chenrui333 He hasn't been affiliated with this for a year or so. Also, please file a new issue for things like this, so that we can triage and respond more effectively.

**Comment by chenrui333** [comment]
Sure, sounds good!
