### ISSUE TITLE
Create an Android app and publish it into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [cloudflare/boringtun#164]

**Comment by Bren2010** [comment]
I believe any external app would need to be part of the WARP client, and we already have an app in the Play Store.

**Comment by KOLANICH** [comment]
>I believe any external app would need to be part of the WARP client

I don't need a warp client. I need an app to connect my own wireguard server on my router. An app that can be run on my extremily old phone (api level 19) with extremily old kernel (one without wireguard).
