### ISSUE TITLE
Add scaffolding needed to support user namespaces

### ISSUE THREAD

**Issue by bbockelm** [cloudflare/boringtun#168]
Modern versions of Linux provide the ability for unprivileged users to create their own namespace - and their own network namespace.

Inside the namespace, we have the ability to create TUN devices and pass the corresponding file descriptor to an external process.  If `boringtun` could utilize an inherited file descriptor (in a manner similar to `wireguard-go`) as the FD corresponding to the TUN device (bypassing any attempts at device creation), we can provide connectivity without elevated privileges (beyond opening a UDP socket).

Similarly, instead of assuming the user API is a named socket on disk, boringtun could provide the ability to inherit a connected end of a `socketpair` from the parent process.  This would allow the parent to completely setup the `boringtun` process without the latter needing any sort of privilege to write into a system directory.

**Comment by vkrasnov** [comment]
Thanks, yes indeed that is a useful functionality, not only for Linux

**Comment by bbockelm** [comment]
@vkrasnov - I had been generally cleaning up the Mac OS X build failures via adding conditional compiles for Linux to the relevant code.  If you think this could function on Macs, I can undo that part.

If you want a motivating use case - I work with a [batch system](https://github.com/htcondor/htcondor) that, in addition to the traditional "cluster" setting, is often deployed at remote locations (often as unprivileged processes within other batch systems).  I'd like to start the payload jobs inside unique network namespaces so they can be inside the "same" network as the central location.

With this, each batch job running on the host can be part of a separate network.  Since the batch system knows exactly what jobs it's running, it can generate (and tear down) peer configurations in the VPN server along with the jobs.

On the server side, I'm also using [slirp4netns](https://github.com/rootless-containers/slirp4netns/) to connect the VPN host to the outside world (using NAT and ip_forward to bridge the `boringtun` and the `slirp4netns` networks).

**Comment by vkrasnov** [comment]
It can function on macOS the same way wireguard-go works within the network-extension without super user privileges. I think someone could find that useful.

**Comment by majek** [comment]
Quick plug: slirpnetstack might be as good if not better than slirp4netns :) https://github.com/majek/slirpnetstack/
