### ISSUE TITLE
UnsatisfiedLinkError using JNI on Windows ?

### ISSUE THREAD

**Issue by WilliamsGest** [cloudflare/boringtun#172]
Hello,

I'm trying to call the function x25519_secret_key() from boringtun.dll to generate a secret key in pure java .

I'm using the following code to perform the call :

![image](https://user-images.githubusercontent.com/6077557/114310689-e67ee500-9aeb-11eb-8b5d-64e8d937b5cd.png)

![image](https://user-images.githubusercontent.com/6077557/114310698-f1d21080-9aeb-11eb-9526-e5d858614d47.png)

However when i run the following code, i got the following exception :

`Exception in thread "main" java.lang.UnsatisfiedLinkError: com/cloudflare/app/boringtun/BoringTunJNI.x25519_secret_key()[B
   at com.cloudflare.app.boringtun.VPNTest.start(VPNTest.java:13)
   at com.cloudflare.app.boringtun.VPNTest.main(VPNTest.java:9)`

However my call seems OK if i look the function described in jni.rs.
Thank you for your help :)

Regards

**Comment by vkrasnov** [comment]
@naga-cf can you help please?

**Comment by Noah-Kennedy** [comment]
I'm closing this as stale.
