### ISSUE TITLE
 ERRO Poll error Interrupted system call (Unable to access interface: Protocol not supported) 

### ISSUE THREAD

**Issue by aakashjonwal89** [cloudflare/boringtun#176]
Hi Team,

I am trying to run wireguard userspace using "boringtun". I have install it properly and set the Path as suggest at the time of installation of boringtun.

But when i try to start wg0 instance using two different way, I got below errors, Can anyone please help to resolve this.

**[root@ip-10-9-20-39 release]# ./boringtun -f wg2
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call
Jun 08 13:37:23.871 ERRO Poll error Interrupted system call**

And when i use " sudo WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun WG_SUDO=1 wg-quick up wg2" command, then error is:

**[root@ip-10-9-20-39 release]# sudo WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun WG_SUDO=1 wg-quick up wg2
[#] ip link add wg2 type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg2
Cannot find device "wg2"**

Please let me know if anyother information required from myend.

Thank You in advance.

**Comment by aakashjonwal89** [comment]
Hi All,

Can anyone help us in this..

**Comment by mikma** [comment]
Have you tried running it with WG_LOG_LEVEL or --verbosity set to trace? Maybe there are some useful output which aren't errors (the default level).

**Comment by aakashjonwal89** [comment]
Hi @mikma ,
Yes i have tried it, and i got below error:

Command which i Run
[root@ip-10-9-20-39 release]#  **./boringtun wg1 --log  --threads --verbosity**
BoringTun failed to start

Error in file is:
[root@ip-10-9-20-39 centos]# tail -f /tmp/boringtun.out
**Jun 10 05:45:01.502 ERRO Failed to initialize tunnel: IOCtl("Invalid argument")**

**Comment by aakashjonwal89** [comment]
Hi Team,

Any suggestion for fix this issue.

**Comment by Noah-Kennedy** [comment]
@aakashjonwal89 are you still having this issue?
