### ISSUE TITLE
 ERRO Failed to initialize tunnel: IOCtl("Invalid argument")

### ISSUE THREAD

**Issue by aakashjonwal89** [cloudflare/boringtun#177]
Hi Team,
I am trying to start the wiregaurd interface using boringtun implementation, So i am run below command.

[root@ip-10-9-20-39 release]#  ./boringtun wg1 --log  --threads --verbosity
BoringTun failed to start

So i recived this error on screen "BoringTun failed to start", and when i checked in log file called "/tmp/boringtun.out". Then its showing below error.

**tail: /tmp/boringtun.out: file truncated
Jun 10 05:55:27.886 ERRO Failed to initialize tunnel: IOCtl("Invalid argument")**

Below is my wg0.conf output. Please check and suggest the correction:
[root@ip-10-9-20-39 release]# cat /etc/wireguard/wg1.conf
[Interface]
PrivateKey = XXXXXXXXXXXXXXXXXXXXXXXXXXX
Address = 10.0.12.89/32

[Peer]
PublicKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AllowedIPs = 10.0.12.30/32
Endpoint = 56.52.10.2:51820
PersistentKeepalive = 25

Please help in this

**Comment by aakashjonwal89** [comment]
Can anyone will update on this...

**Comment by aakashjonwal89** [comment]
Hi Team,
Any suggestions for fix this issue

**Comment by irctrakz** [comment]
Looks like your subnet is wrong on the Interface, I assume you're using wg-quick which IMHO horribly abstracts away what's happening.

I'd guess you should set the interface address to `10.0.12.89/24`, or even better bring it up manually:

`ip addr add 10.0.12.89/24 dev wg0`

**Comment by Noah-Kennedy** [comment]
@aakashjonwal89 I'm closing this as stale. If you are still having issues we can reopen it.
