### ISSUE TITLE
Is boringtun production ready?

### ISSUE THREAD

**Issue by alisafari1998** [cloudflare/boringtun#180]
As it's mentioned in [Cloudflare's blog post](https://blog.cloudflare.com/boringtun-userspace-wireguard-rust/) back in 2019 `BoringTun is currently under internal security review, and it is probably not fully ready to be used in mission critical tasks.` but there isn't any new information on this topic.

Also I'm concerned about following things:
- Does any enterprise service use this project under heavy load?
- What is Cloudflare's active use of this project?
- Are there any limitations on using this project instead of official solution of Wireguard?

**Comment by Bren2010** [comment]
boringtun is a building block of [WARP client](https://1.1.1.1/) and our [Cloudflare for Teams](https://www.cloudflare.com/teams/) product. Any limitations are documented in the project's [license](https://github.com/cloudflare/boringtun/blob/master/LICENSE.md) file.
