### ISSUE TITLE
Boringtun always in the process .

### ISSUE THREAD

**Issue by fscarmen** [cloudflare/boringtun#197]
I use ``` wg-quick down wgcf ``` or  ```WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun WG_SUDO=1 wg-quick down wgcf``` to close wireguard.

Then i use ``` ps -axj | grep boringtun ```. It is still running. I have to use ```kill $(pgrep -f boringtun)```.

Could I use a command to close it automatically?

![image](https://user-images.githubusercontent.com/62703343/136948094-5b64f262-0d55-4f75-ab28-ca9d6dc60b32.png)

**Comment by brlin-tw** [comment]
This is a known bug, refer: 

https://github.com/cloudflare/boringtun/issues/125

**Comment by fscarmen** [comment]
> This is a known bug, refer:
> 
> #125

Is there  a "boringtun.service" file ,which let BoringTUN runs automatically after reboot?

And how do you turn it off . I ran ```wg-quick down wgcf; kill $(pgrep -f boringtun)```.
If i don't . It will use 100% CPU.

**Comment by Noah-Kennedy** [comment]
@fscarmen are you using the boringtun from the master branch?

**Comment by fscarmen** [comment]
@Noah-Kennedy i installed it using cargo

**Comment by Noah-Kennedy** [comment]
If you just called `cargo install boringtun`, then you are using a version which is quite old. Can you please try this with the latest version from the master branch?

**Comment by Noah-Kennedy** [comment]
For the record, a new release should be coming out soon.

**Comment by Noah-Kennedy** [comment]
Closing as stale. @fscarmen feel free to reopen if this is still an issue.
