### ISSUE TITLE
feature: Support for Mac Catalyst

### ISSUE THREAD

**Issue by learnerBing** [cloudflare/boringtun#204]
I am using the following command to build the library for Mac catalysts.

`cargo +nightly build -Z build-std --lib --target x86_64-apple-ios-macabi`

but when I try to build the app for MacBook (mac catalyst) using the resulting static library by the above code I get the following error.

`Error: /boringtun/target/x86_64-apple-ios-macabi/release/libboringtun.a(chacha-x86_64-macosx.o), building for Mac Catalyst, but linking in object file built for macOS,`

apparently, **chacha** is being built for macOS. 

I tried to build again after removing **ring**, that worked alright.

Edit:
I had to remove Mac catalyst, conditional compilation checks like the following ones. to remove ring.
`#[cfg(not(target_arch = "arm"))]`
 
 
 I wonder what it would be for mac catalyst ?

**Comment by Noah-Kennedy** [comment]
@learnerBing you can always open a PR for this.

**Comment by Noah-Kennedy** [comment]
Closing this as stale.
