### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aramperes** [cloudflare/boringtun#207]
There have been [lots of changes](https://github.com/cloudflare/boringtun/compare/v0.3.0...master) since the last release in April 2020. A new release published to `crates.io` would be appreciated for [other projects](https://github.com/aramperes/onetun) that depend on `boringtun` as a library (in order for them to be published as well).

**Comment by Noah-Kennedy** [comment]
I'm actually working on this right now, and am hoping to get this out in the next few days.

**Comment by luv2dnce33** [comment]
any update?

**Comment by Noah-Kennedy** [comment]
Sorry about that. A few things came up and I lacked the bandwidth at the time. This is awaiting the review of several PRs, which should be done next week. After that, I will publish. Currently the android build is broken which is blocking a new release.

**Comment by Noah-Kennedy** [comment]
@luv2dnce33 @aramperes it's live now

**Comment by luv2dnce33** [comment]
@Noah-Kennedy can you push 0.6.0 so Brew can receive the latest updates?

**Comment by Noah-Kennedy** [comment]
I can do so this weekend, I am out of town right now.

**Comment by luv2dnce33** [comment]
At your leisure, thank you friend!

**Comment by luv2dnce33** [comment]
Anything for this one yet?
