### ISSUE TITLE
android build is broken again due to recent changes

### ISSUE THREAD

**Issue by saurik** [cloudflare/boringtun#211]
In a133f1df70e09052f3fabdcd50cba98d299b0e51 a new argument was added to new_tunnel for the preshared_key, but the usage in src/jni.rs was not updated.

https://github.com/cloudflare/boringtun/blob/a133f1df70e09052f3fabdcd50cba98d299b0e51/src/jni.rs#L148-L155

**Comment by Noah-Kennedy** [comment]
@saurik would you be willing to open a PR for this?

**Comment by Noah-Kennedy** [comment]
Nevermind, I took care of it

**Comment by Noah-Kennedy** [comment]
@saurik it will not work until #214 is merged.

**Comment by saurik** [comment]
@Noah-Kennedy For avoidance of any doubt, #214 is now merged, but the Android build still doesn't work (due to the private module import). In case it is useful to reference this directly: this is broken because of 75a548577d85c9761dfd6d1412606e6ff0fb9006, which removed the public export of the x25519 module and replaced it with direct exports of only x25519::X25519SecretKey and x25519::X25519 PublicKey.

**Comment by Noah-Kennedy** [comment]
@saurik looking again, I'm not sure what I was thinking when I said that, yeah this should be unaffected by #214. Could you make a PR with your patch?

**Comment by saurik** [comment]
https://github.com/cloudflare/boringtun/pull/218
