### ISSUE TITLE
Stack gets overflowed while adding peers via wg setconf and wg addconf commands

### ISSUE THREAD

**Issue by zaid3tech** [cloudflare/boringtun#230]
Hi, I opened this issues few days ago #222.
Whenever I try to add almost 24000 peers with `wg addconf` at some point the stack gets overflowed and tunnel panics. I have solved this issue for my use case, would you like to review my code?

**Comment by Noah-Kennedy** [comment]
@zaid3tech Let's move this discussion over to the other issue.
