### ISSUE TITLE
Documentation about `sudo` permission to run `boringtun`

### ISSUE THREAD

**Issue by chenrui333** [cloudflare/boringtun#236]
👋  as followup of [this comment](https://github.com/cloudflare/boringtun/issues/161#issuecomment-1061298280), I wonder if there is any documentation for the permission change to run `boringtun`, thanks! 

cc @Noah-Kennedy

**Comment by Noah-Kennedy** [comment]
I don't think that there is. Boringtun went kinda unmaintained for a while, and the new group (including myself) that recently took over maintenance of it are finding lots of knowledge lost to the winds of time.

**Comment by Noah-Kennedy** [comment]
I'm going to close this issue for now, since there isn't anything actionable here.
