### ISSUE TITLE
BoringTun initiates a new session exactly every 2 minutes

### ISSUE THREAD

**Issue by aofei** [cloudflare/boringtun#237]
OS: Ubuntu 20.04
BoringTun: WARP 2022.2.288

---

I noticed in the `warp-svc` logs (see pic below) that the `boringtun` kept creating new sessions. I've never seen similar behavior in the official [`wireguard`](https://www.wireguard.com/install/#ubuntu-module-tools) client before, so I'm wondering if this is an expected behavior? It feels weird. Not sure if it will cause the upper-layer connections to be interrupted or something.

Hope for an answer. Thanks~ ❤️

![Screen Shot 2022-03-12 at 02 03 37](https://user-images.githubusercontent.com/5037285/157927150-feb16782-f263-4c39-97b6-9b1ddd765233.png)

**Comment by jeff-hiner** [comment]
This is a response to re-keying. The REKEY_AFTER_TIME interval is set by the protocol, and the jitter is a relatively narrow fixed range (0-333ms).

https://www.wireguard.com/protocol/
"Future work involves adjusting `REKEY_TIMEOUT` to use exponential back-off.
