### ISSUE TITLE
Usage of CPU features (SSE)

### ISSUE THREAD

**Issue by sh7dm** [cloudflare/boringtun#246]
SSE is known of being able to accelerate ChaCha20 cipher, which is the main cryptographic primitive behind WireGuard. Adaptively enabling SSE on capable hardware could increase performance and energy efficiency of implementation.
Kernel implementation does use hardware acceleration via Crypto API

**Comment by sh7dm** [comment]
If this is considered useful I might try myself in vectorizing the ChaCha20 implementation included in Boringtun.

**Comment by Noah-Kennedy** [comment]
@sh7dm PRs are welcome.

**Comment by sh7dm** [comment]
Great, will try soon!

**Comment by sh7dm** [comment]
My own SSE2 impl was not better than default (Rust should have been assuming SSE2 for x86_64 target), but manually enabling compiler's own AVX2 boosted the perf:
`cargo bench`:
<details>

```
test tests::bench_blake2s_hash_1024b          ... bench:       5,223 ns/iter (+/- 28)
test tests::bench_blake2s_hash_128b           ... bench:         721 ns/iter (+/- 8)
test tests::bench_chacha20poly1305_open_192b  ... bench:       1,380 ns/iter (+/- 12)
test tests::bench_chacha20poly1305_seal_192b  ... bench:       1,784 ns/iter (+/- 8)
test tests::bench_chacha20poly1305_seal_512b  ... bench:       4,694 ns/iter (+/- 52)
test tests::bench_chacha20poly1305_seal_8192b ... bench:      70,136 ns/iter (+/- 249)
test tests::bench_x25519_public_key           ... bench:     113,748 ns/iter (+/- 796)
test tests::bench_x25519_shared_key           ... bench:     113,860 ns/iter (+/- 661)
```

</details>

`RUSTFLAGS="-C target-feature=+avx2" cargo bench`:
<details>

```
test tests::bench_blake2s_hash_1024b          ... bench:       5,267 ns/iter (+/- 33)
test tests::bench_blake2s_hash_128b           ... bench:         738 ns/iter (+/- 2)
test tests::bench_chacha20poly1305_open_192b  ... bench:       1,375 ns/iter (+/- 2)
test tests::bench_chacha20poly1305_seal_192b  ... bench:       1,265 ns/iter (+/- 17)
test tests::bench_chacha20poly1305_seal_512b  ... bench:       2,288 ns/iter (+/- 39)
test tests::bench_chacha20poly1305_seal_8192b ... bench:      31,186 ns/iter (+/- 299)
test tests::bench_x25519_public_key           ... bench:     114,478 ns/iter (+/- 1,869)
test tests::bench_x25519_shared_key           ... bench:     114,803 ns/iter (+/- 1,204)
```

</details>

It might be worth it to build both and switch between them (build shared libraries and dynamically load them).

Benchmarked machine:
Ryzen 5 4500U (powersave governor, locked to 1400 MHz for test stability)
Fedora Linux 35 (kernel 5.16)

**Comment by jeff-hiner** [comment]
We switched to `ring`, because maintaining our own chacha20 implementation isn't something we want to do. Performance should already be far better, as it seems to build with the avx2 intrinsics.

**Comment by ExternalReality** [comment]
I'd be interested to see how performance improves under [AVX512 and Intel QAT](https://builders.intel.com/docs/networkbuilders/intel-avx-512-and-intel-qat-accelerate-wireguard-processing-with-intel-xeon-d-2700-processor-technology-guide-1647024663.pdf).

Also, I think the move to Mio/Tokio might open up more opportunities for hardware based improvements.
