### ISSUE TITLE
Tools other than `wg(8)` to configure BoringTun

### ISSUE THREAD

**Issue by arinc9** [cloudflare/boringtun#250]
It's being hinted at the readme that we can configure the tunnel using `wg(8)` or any other tool.

My problem is that I want to use BoringTun on a network which blocks the WireGuard header for handshake and transport data which,  if I understand correctly, is constructed by `wg(8)`.

Looking at the packet capture, WARP doesn't seem to use `wg(8)` to configure BoringTun as Wireshark doesn't see the WireGuard header on the UDP packets. Therefore, it works on my network.
(The WARP server [engage.cloudflareclient.com] still listens to WireGuard handshake packets for some reason.)

I'm not aware of any other tools I can use to configure the BoringTun interface. Is the one for WARP open source?

**Comment by Noah-Kennedy** [comment]
The WARP client is not open source and uses its own internal configuration management system. I don't think that simply changing the configuration will let you connect over this network.

I'd like to add support to boringtun for QUIC tunneling using quiche at some point, but I don't have enough bandwidth right now to get to this anytime soon. I already need to significantly rewrite large portions of this tool and library to work off of tokio, and maybe this can be done afterwards.
