### ISSUE TITLE
Create GitHub Actions pipelines

### ISSUE THREAD

**Issue by KOLANICH** [cloudflare/boringtun#262]
We also need artifacts to be published after each build.

**Comment by Noah-Kennedy** [comment]
@KOLANICH Who needs this? Not sure who is being referred to by "we".

**Comment by KOLANICH** [comment]
CF doesn't need it? OK.

**Comment by Noah-Kennedy** [comment]
@KOLANICH I am

**Comment by KOLANICH** [comment]
I want to implement a GH Actions testing pipeline for my python bindings to BoringTun. So I need a way to fetch the latest prebuilt shared library (`cdylib`) without building it myself every time.

**Comment by Noah-Kennedy** [comment]
Ah.

**Comment by Noah-Kennedy** [comment]
I'm working on changing our CI over to GitHub Actions from Azure CI for this repo. Once I merge #244 (probably tomorrow), I can start setting up something to automatically post artifacts when tags get merged to master.

**Comment by Noah-Kennedy** [comment]
Closing this as done since #26 covers the remaining work.
