### ISSUE TITLE
Tunnel crash observed with the latest release.

### ISSUE THREAD

**Issue by zaid3tech** [cloudflare/boringtun#294]
Hye! First of all, thanks for the new release, I recently got into this problem after upgrading to 0.5.0, the tunnel crashed twice for me with the following logs any help will be appreciated.
Logs
> thread ‘<unnamed>’ panicked at ‘source slice length (16) does not match destination slice length (32)‘, boringtun/src/noise/rate_limiter.rs:138:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread ‘<unnamed>’ panicked at ‘source slice length (16) does not match destination slice length (32)‘, boringtun/src/noise/rate_limiter.rs:138:26
thread ‘<unnamed>’ panicked at ‘source slice length (16) does not match destination slice length (32)‘, boringtun/src/noise/rate_limiter.rs:138:26
thread ‘<unnamed>’ panicked at ‘source slice length (16) does not match destination slice length (32)’, boringtun/src/noise/rate_limiter.rs:138:26
thread ‘main’ panicked at ‘called `Result::unwrap()` on an `Err` value: Any { .. }’, boringtun/src/device/mod.rs:179:27

**Comment by Noah-Kennedy** [comment]
@jeff-hiner

**Comment by jeff-hiner** [comment]
Looks like we missed limiting/truncating a destination buffer. `split_array_ref` would have caught this but it's still not stabilized yet.

**Comment by Noah-Kennedy** [comment]
@zaid3tech This should be fixed in the new version we just released (v0.5.1). Could you please try it and reopen if it breaks again?

**Comment by zaid3tech** [comment]
Thank you!
Upgrading to v0.5.1 now will reopen if it breaks.
