### ISSUE TITLE
Add homebrew formula

### ISSUE THREAD

**Issue by dknecht** [cloudflare/boringtun#32]
Make it easy to install on the Mac.

**Comment by Noctem** [comment]
@Homebrew will presumably want a release tarball that doesn't have "TEST" in the name and that isn't cut from an experimental branch.

In the meantime you're welcome to use [this formula](https://github.com/Noctem/homebrew-custom/blob/master/boringtun.rb) from my tap:
```sh
brew install --HEAD https://raw.githubusercontent.com/Noctem/homebrew-custom/master/boringtun.rb
```
(you can also `brew tap` that repo, but it includes other unrelated things)

**Comment by Noctem** [comment]
I see that a proper release has been made so I've created a PR here: Homebrew/homebrew-core#38533

Let me know if there's anything that should be changed.

**Comment by zbeekman** [comment]
The release seems to have vanished... what gives?

**Comment by vkrasnov** [comment]
Looks like it was removed by mistake, I pushed it back

**Comment by zbeekman** [comment]
😅

**Comment by luv2dnce33** [comment]
can you update the formula for brew to 0.4.0?

**Comment by Noah-Kennedy** [comment]
@luv2dnce33 we don't maintain that release channel afaik. I'd open up a PR or issue with homebrew-core.

**Comment by luv2dnce33** [comment]
I did talk to the team and they said:

`I see the problem in here, they did not mark the release tag in github.`

_Originally posted by @chenrui333 in https://github.com/Homebrew/homebrew-core/issues/52625#issuecomment-1059845034_
