### ISSUE TITLE
Can I use boringtun (Cloudflare’s 1.1.1.1 + WARP) alongside with our company VPN 

### ISSUE THREAD

**Issue by suntong** [cloudflare/boringtun#329]
Can I use boringtun (Cloudflare’s 1.1.1.1 + WARP) alongside with our company/school VPN?

Maybe not, as they'll both fight for the DNS resolvement, I'd presume.  
Just want a clarification.

Thanks

**Comment by Noah-Kennedy** [comment]
This is probably a better question for our discord or another forum for user and developer discussion that we have. This is for discussing the boringtun wireguard implementation.

To answer your question, you can probably make this work, depending on the VPN, although this may require some fiddling. I'd recommend messing with the split-tunnel facilities that we have.
