### ISSUE TITLE
How does warp use same allowedIP(172.16.0.2/32) for all of their clients ?

### ISSUE THREAD

**Issue by alom4hdi** [cloudflare/boringtun#342]

**Comment by Noah-Kennedy** [comment]
Normal wireguard usages create a virtual network topology via peers and allowed ips. Warp doesn't do this, as it basically creates a separate, single-peer topology for every client, so it is free to assign them all the same IP within the tunnel.

I'm closing to keep down noise as it's not really a question about boringtun, but we can still discuss this further in the thread.

**Comment by alom4hdi** [comment]
@Noah-Kennedy Thanks.
Can you give me more details about warp topology ?
Can I setup a wireguard server with that topology using boringtun or I should build a wireguard implementation for that ?

**Comment by Noah-Kennedy** [comment]
@alom4hdi at this point we'd be talking about implementing the wireguard protocol, but not the behavioral spec. You'd need your own implementation that uses wg's peer communications, but does routing, natting, etc a bit differently.

**Comment by b00tkitism** [comment]
@Noah-Kennedy Hi again, i'm sorry for bothering you, but I spent the last 2 months working on an implementation of a WireGuard server like WARP, but I couldn't achieve anything. Can you give me a more detailed explanation of how WARP servers work? Or any open-source codes?

**Comment by b00tkitism** [comment]
@Noah-Kennedy ?
