### ISSUE TITLE
Use make_array instead manually defining arrays where appropriate

### ISSUE THREAD

**Issue by kpp** [cloudflare/boringtun#42]
https://github.com/cloudflare/boringtun/blob/3c9c01c7361f321e54c687bb8d099a0398d6692a/src/noise/mod.rs#L271

https://crates.io/crates/byteorder

**Comment by hellow554** [comment]
(I'm not a member of cloudfare) I don't see any strong reason to pull the byteorder crate in. Rust natively supports these functions since 1.32.0 and if you do not target lower versions of the compiler this is completly fine IMHO.

**Comment by kpp** [comment]
u32::from_le_bytes(make_array(&self.buf[0..])),

**Comment by vkrasnov** [comment]
I try to keep dependencies that use unsafe rust to a minimum. Also using `from_le_bytes + make_array` results in a single mov instruction emitted.

**Comment by kpp** [comment]
Then use from_le_bytes + make_array. No need to close this issue until you have synchronized style for parsing raw bytes. You can rename my issue.

**Comment by vkrasnov** [comment]
That is a valid point
