### ISSUE TITLE
Doesn't work with sudo

### ISSUE THREAD

**Issue by bugworm** [cloudflare/boringtun#44]
```
$ sudo WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun wg-quick up wg0
sudo: sorry, you are not allowed to set the following environment variables: WG_QUICK_USERSPACE_IMPLEMENTATION
```
Works fine without sudo(asks a password) and from root.
Arch Linux, was installed from AUR(it's pretty much just `cargo build --release`)

**Comment by vkrasnov** [comment]
I think you might have to do something like
`sudo env WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun wg-quick up wg0`
On Arch Linux.

**Comment by bugworm** [comment]
yeah, that works.

**Comment by vkrasnov** [comment]
I will add that to README, thank you.
