### ISSUE TITLE
Timer problem in virtualized environment

### ISSUE THREAD

**Issue by engelmarkus** [cloudflare/boringtun#51]
Hi there,
I'm trying to run boringtun on a vServer that uses virtuozzo as its hypervisor and it exits immediately with the following message:
```
~> sudo boringtun -f -v debug wg0 
Timer("Invalid argument")
~> 
```

The system:
```
~> uname -a
Linux **** 4.15.0 #1 SMP Thu Feb 21 17:35:43 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
~> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
~> rustup show
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.33.0 (2aa4c46cf 2019-02-28)
~> 
```

Have you got any clue what could be causing this?

Regards,
Markus

**Comment by vkrasnov** [comment]
My guess would be some problem using `timer_fd` with `CLOCK_BOOTTIME`

**Comment by engelmarkus** [comment]
Indeed, that's the problem, thank you!
```
~> cat test.c
#include <errno.h>
#include <stdio.h>
#include <sys/timerfd.h>

int main() {
	errno = 0;
	int fd1 = timerfd_create(CLOCK_BOOTTIME, 0);

	perror(NULL);

	errno = 0;
	int fd2 = timerfd_create(CLOCK_MONOTONIC, 0);

	perror(NULL);
}
~> gcc -o test test.c
~> sudo ./test
Invalid argument
Success
~> 
```

https://github.com/cloudflare/boringtun/blob/e765e12613e8eb33e39e7fb0676ad5797c02c5f6/src/device/epoll.rs#L104

So I think I could change this to `CLOCK_MONOTONIC` when I can guarantee that the system won't be suspended as long as boringtun is running?

**Comment by vkrasnov** [comment]
That is right
