### ISSUE TITLE
Validate allowed_ips for overlapping addresses

### ISSUE THREAD

**Issue by Lekensteyn** [cloudflare/boringtun#57]
If a two peers are added with `0.0.0.0/0`, then that should probably be rejected with an error. Based on `$insert` in allowed_ips.rs and the code below, it looks like the current behavior is to silently overwrite existing peers. Not sure if that is desirable.

```rust
    fn update_peer(
        // ...
        allowed_ips: Vec<AllowedIP>,
        // ...
    ) {
        // ...
        for AllowedIP { addr, cidr } in allowed_ips {
            self.peers_by_ip.insert(addr, cidr as _, Arc::clone(&peer));
        }
```

It would be nice to have tests as well. One thing I am not entirely sure about is how to handle overlapping ranges, e.g. `10.1.2.0/24` and `10.1.2.100/32`.

**Comment by vkrasnov** [comment]
No, the correct behavior is to override the previous peer, which boringtun does. Check https://www.wireguard.com/xplatform/:

```
allowed_ip: The value for this is IP/cidr, indicating a new added allowed IP entry for the previously added peer entry. If an identical value already exists as part of a prior peer, the allowed IP entry will be removed from that peer and added to this peer.
```
