### ISSUE TITLE
Result::is_ok used incorrectly

### ISSUE THREAD

**Issue by alex** [cloudflare/boringtun#62]
- https://github.com/cloudflare/boringtun/blob/master/src/device/api.rs#L19
- https://github.com/cloudflare/boringtun/blob/master/src/device/api.rs#L43

Both of these seem to be trying to use it as an assertion, however `Result::is_ok()` simply returns a `bool`. I think both of these should be using `expect()` instead.

**Comment by alex** [comment]
It occurs to me that maybe the intent here was to silence the `#[must_use]` on `Result`. If that's the intent, I think the convention is to do `let _ = <ignored expression>;` instead, which is much clearer about what you're doing.

**Comment by alex** [comment]
`Result::ok()` is used in the same way in a bunch of places. One example: https://github.com/cloudflare/boringtun/blob/master/src/main.rs#L148

This example is dangerous because it means errors in dropping privileges (i.e. the process is still `root`) are ignored.

**Comment by Lekensteyn** [comment]
The drop privileges issue is tracked in #48.

**Comment by vkrasnov** [comment]
You are right about must use suppression, since creating a directory will fail if it already exists, and removing a file will fail if it does not exist. In both cases we don't really care what happens.

I actually assumed that `.is_ok()` is so much prettier than other options, but maybe it is not idiomatic.

**Comment by ayosec** [comment]
> I actually assumed that `.is_ok()` is so much prettier than other options, but maybe it is not idiomatic.

IMO, `let _ = create_dir(SOCK_DIR);` is better, since the intention (ignore the result) is more explicit.

**Comment by zrzka** [comment]
> I actually assumed that `.is_ok()` is so much prettier than other options, but maybe it is not idiomatic.

It's not idiomatic. What ayosec did wrote (`let _ = ...`) is.
