### ISSUE TITLE
Relation to Wireguard upstream

### ISSUE THREAD

**Issue by HazCod** [cloudflare/boringtun#63]
Reading this post from one of the Wireguard maintainers: https://lists.zx2c4.com/pipermail/wireguard/2019-March/004048.html

Are there any specific reasons for not sharing changes upstream?
It's great that a company like Cloudflare uses an opensource project to work with, but refusing to join in on the project seems counterproductive.

Is there an official stance on this?

**Comment by jgrahamc** [comment]
See https://news.ycombinator.com/item?id=19545376
