### ISSUE TITLE
`Failed to drop privileges: DropPrivileges("NULL from getlogin")`

### ISSUE THREAD

**Issue by vi** [cloudflare/boringtun#75]
When started from root, it fails:

```
# boringtun -f wg0
Failed to drop privileges: DropPrivileges("NULL from getlogin")
```

With `--disable-drop-privileges` it goes through.

`getlogin` is [said](https://stackoverflow.com/a/4785195/266720) to be a non-recommended way of determining user.

**Comment by vkrasnov** [comment]
Thank you. I intend to add an option of specifying user and group via the cli.

**Comment by yaoshenshen** [comment]
when I run  root
./boringtun -f wg0
Failed to drop privileges: DropPrivileges("Failed to permanently drop privileges")

if this error is a bug  ?

**Comment by soarway** [comment]
[root@VM-16-13-centos release]#  ./boringtun -f wg0
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Poll error Interrupted system call
Feb 03 19:29:20.971 ERRO Failed to drop privileges: DropPrivileges("Failed to permanently drop privileges")
