### ISSUE TITLE
iOS Configuration

### ISSUE THREAD

**Issue by jmayalag** [cloudflare/boringtun#83]
I'm trying to piece out how to integrate with NEPacketTunnelProvider, however I can't figure out how to configure the tunnel. The **wireguard-go** api allows one to create the tunnel with the settings from the .conf file, but boringtun's ffi only allows me to set the private key and server public key.

How can the configuration be accomplished using the borintun lib?

**Comment by vkrasnov** [comment]
boringtun library is mostly intended to be used as a "client" peer configuration, with one or very few "server" peers.
A typical wireguard config includes:
your private key - you pass it when you create the tunnel
server public key - you pass that as well

The rest are using: [setTunnelNetworkSettings](https://developer.apple.com/documentation/networkextension/netunnelprovider/1406539-settunnelnetworksettings) and [NEIPv4Settings](https://developer.apple.com/documentation/networkextension/neipv4settings) or [NEIPv6Settings](https://developer.apple.com/documentation/networkextension/neipv6settings)

[address](https://developer.apple.com/documentation/networkextension/neipv4settings/1406666-addresses)
[allowed ips](https://developer.apple.com/documentation/networkextension/neipv4settings/1406654-includedroutes)
[dns](https://developer.apple.com/documentation/networkextension/netunnelnetworksettings/1406331-dnssettings)

The endpoint is simply where you connect your UDP connection.
