### ISSUE TITLE
cli option --disable-drop-privileges incompatible with wg-quick

### ISSUE THREAD

**Issue by mash-graz** [cloudflare/boringtun#86]
in the context of docker cointainers, where `boringtun` is executed by `UID 0`, we have to utilize `--disable-drop-privileges`, but this workaround isn't available, if we have to use the `WG_QUICK_USERSPACE_IMPLEMENTATION` environment variable to instruct `wg-quick` to use `boringtun`. in this case it isn't possible to specify any additional user space tool command line options and `wg-quick` will not work because of boringtuns drop privileges related troubles.

maybe we could workaround this issue by:

* calling a symbolic link pointing to `boringtun` under a different name (e.g. `boringtun-ddp`), which behaves like `boringtun --disable-drop-privileges`,
 
* or we have to modify `wg-quick` to allow specifing this needed additional flag

* or change the default behavior in case of execution under `UID 0` ...

**Comment by vkrasnov** [comment]
How about an env variable?

**Comment by mash-graz** [comment]
yes -- that's another possibility... :+1: 

we just need a simple and user friendly solution, which does not need to much modifications in other exiting programs/scripts...
