### ISSUE TITLE
expected i16, found i32 in tun_linux.rs

### ISSUE THREAD

**Issue by neutronscott** [cloudflare/boringtun#89]
I have never used Rust so I am sorry if I am not much use in solving this. I wanted a userspace wireguard in OpenVZ. I apply the CLOCK_BOOTTIME fix #73 but get:

```
   Compiling boringtun v0.2.0
error[E0308]: mismatched types
  --> /home/mute/.cargo/registry/src/github.com-1ecc6299db9ec823/boringtun-0.2.0/src/device/tun_linux.rs:77:29
   |
77 |                 ifru_flags: IFF_TUN | IFF_NO_PI | IFF_MULTI_QUEUE,
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected i16, found i32
```

I circumvented this by changing the ifru_flags to c_int. It seems to work and didn't look like it was in master branch or covered in an issue.

This may be because changes missing/applied to libc. I have libc-0.2.58:

```
mute@atl:~/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.58/src/unix/notbsd/linux$ grep -e IFF_TUN -e IFF_NO_PI -e IFF_MULTI_QUEUE *.rs
mod.rs:pub const IFF_TUN: ::c_int = 0x0001;
mod.rs:pub const IFF_NO_PI: ::c_int = 0x1000;
mod.rs:// TUN device type flags: deprecated. Use IFF_TUN/IFF_TAP instead.
mod.rs:pub const TUN_TUN_DEV: ::c_short   = ::IFF_TUN as ::c_short;
mod.rs:pub const IFF_TUN_EXCL: ::c_int     = 0x8000;
mod.rs:pub const IFF_MULTI_QUEUE: ::c_int  = 0x0100;
```

```
mute@atl:~$ rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
```

**Comment by Daniel15** [comment]
I hit this issue too. Thanks for the fix - Changing `ifru_flags` from `c_short` to `c_int` on this line fixed the build for me too: https://github.com/cloudflare/boringtun/blob/1f842a618a4efb460841a3e0104f4979b21a2485/src/device/tun_linux.rs#L27

**Comment by vkrasnov** [comment]
Thank you, another solution is to do `(IFF_TUN | IFF_NO_PI | IFF_MULTI_QUEUE) as _` to keep it compatible with other platforms
