### ISSUE TITLE
"boringtun failed to start"

### ISSUE THREAD

**Issue by Daniel15** [cloudflare/boringtun#90]
This error doesn't give much debugging info, unfortunately:
```
root@vps12:/home/daniel# boringtun --verbosity debug wg0
boringtun failed to start

root@vps12:/home/daniel# cat /tmp/boringtun.err

root@vps12:/home/daniel# cat /tmp/boringtun.out
Success, daemonized
Timer("Invalid argument")
```

Debian 9 (Stretch) on an OpenVZ VPS.

**Comment by neutronscott** [comment]
That's the timer thing I mentioned in my issue. See https://github.com/cloudflare/boringtun/pull/73 for fix

**Comment by neutronscott** [comment]
I also used a couple command line options to get it going after that:
```
root/boringtun -f --disable-multi-queue --disable-drop-priviliges -v debug wgnet0
```

**Comment by vkrasnov** [comment]
@Daniel15 were you able to solve the problem?

**Comment by Daniel15** [comment]
I haven't tried it again, I ended up using wireguard-go instead. I'll close out this issue as it seems linked the linked PR fixes it.

**Comment by compuwar** [comment]
encountered today after nstallng the crate.

strace shows timerfd_create(CLOCK_BOOTTIME, TFD_NONBLOCK) = -1 EINVAL (Invalid argument)
