### ISSUE TITLE
wg complains 'Unable to modify interface: Unknown error -98'

### ISSUE THREAD

**Issue by Jimmy-Z** [cloudflare/boringtun#92]
Debian 9, default kernel 4.9
rustc version 1.36.0
wg from WireGuard-0.0.20190702.tar.xz

`# boringtun -f -v debug wg1` either doesn't output anything or this:
```
Poll error Interrupted system call
Poll error Interrupted system call
Poll error Interrupted system call
Poll error Interrupted system call
Poll error Interrupted system call
Poll error Interrupted system call
Poll error Interrupted system call
```

README.md says 
> The tunnel can then be configured using wg, as a regular WireGuard tunnel, or any other tool.
but
```
# wg setconf wg1 /etc/wireguard/conf
Unable to modify interface: Unknown error -98
```
`/tmp/boringtun.err` is empty and `/tmp/boringtun.out` contains only one line:
```
Success, daemonized
```

What am I doing wrong?

**Comment by vkrasnov** [comment]
wg always sets fwmark (even if to 0) therefore you should start boringtun with `--disable-drop-privileges` or give it net admin capabilities using `sudo setcap cap_net_admin+epi boringtun`

**Comment by Jimmy-Z** [comment]
Thanks for the quick reply, but I tried again with `--disable-drop-privileges`, and I'm running it as root, wg complains the same.

I'll try again with an older wg.

**Comment by Jimmy-Z** [comment]
update: tried with wg 0.0.20190406, same result.

**Comment by vkrasnov** [comment]
which directives do you use in the config file?

**Comment by Jimmy-Z** [comment]
My bad, I have the kernel module running with the same conf as wg0, I thought that won't be a problem until I realize the ListenPort will conflict.

**Comment by Jimmy-Z** [comment]
I'd suggest you to add 'wg always sets fwmark' in README.md, I admit I didn't read the README fully but I wouldn't be able to link the problem to that even if I did read the README.

**Comment by antnks** [comment]
It took a while for me to troubleshoot the same issue until I found this closed topic. I would agree that a lot of people are trying to run `sudo boringtun` and get the same error. So, at least mention the error `Unable to modify interface: Unknown error -98` in README, so it becomes searchable, or print more verbose error saying "if you run with sudo please check README for a solution"
